version: "3"

services:
  svc:
    container_name: "greenadam-services"
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - pg
    volumes:
      - ./:/app
    env_file:
      - "vars.env"
    environment:
      POSTGRES_PORT: 5432
  pg:
    image: "postgres"
    container_name: "greenadam-postgres"
    restart: unless-stopped
    env_file:
      - "vars.env"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    # To keep data on host system use volumes
    #volumes:
    #  - /opt/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      # Please, set external_port that suits you
      # "external_port:internal_port"
      - "55400:5432"

volumes:
  pgdata:

