global:
  extractor:
    # Seconds to sleep between updates/retries
    sleep_time: 1200
  martmaker:
    # Seconds to sleep between updates/retries
    sleep_time: 30
db:
  entities:
    - mission
    - rocket
    - launch
  # Schema to maintain filling order for the database
  schema:
    mission:
        order:
          - mission
    rocket:
        order:
          - rocket
    launch:
        order:
          - launch
